### ISSUE TITLE
Post History View Liked Button Not Working

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#80] opened 2015-10-31 21:56 UTC
If you like a song, it should show as previously liked in Post History View
![img_0605](https://cloud.githubusercontent.com/assets/7467062/10866116/92fc86e4-7ff8-11e5-8439-7f0d68669bb3.jpg)
![img_0606](https://cloud.githubusercontent.com/assets/7467062/10866117/95e286e2-7ff8-11e5-8948-e18954def2fc.jpg)

**Comment by lucasderraugh** [comment] 2015-11-01 09:29
Does this only happen with other people's profiles. I can't reproduce otherwise.

**Comment by say25** [comment] 2015-11-03 04:36
No longer an issue.

**Comment by lucasderraugh** [comment] 2015-11-03 04:37
What resolved this?

**Comment by say25** [comment] 2015-11-03 04:45
Liking and unliking not handled in post history view

**Comment by lucasderraugh** [comment] 2015-11-10 05:25
Fixed in web commit https://github.com/cuappdev/icefishing-web/commit/1d3a835812a9a83fe4e09db1598c090c7264fbb0

**Closed by lucasderraugh** 2015-11-10 05:25 UTC
Labels: bug
